# Generated by Django 4.0.2 on 2022-02-13 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(verbose_name='Старт')),
                ('ended', models.DateTimeField(verbose_name='Конец')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на сервис',
                'verbose_name_plural': 'Подписки на сервис',
                'ordering': ('started',),
            },
        ),
    ]
