# Generated by Django 4.0.2 on 2022-04-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'ordering': ('started',)},
        ),
        migrations.AddField(
            model_name='subscribe',
            name='address',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='subscribe',
            name='social_media',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='ended',
            field=models.DateTimeField(verbose_name='Ended'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='started',
            field=models.DateTimeField(verbose_name='Started'),
        ),
    ]
